---
title: "Quem são os mais ricos (parte 2)?"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(dplyr)
library(devtools)
library(DT)
library(flexdashboard)
library(knitr)
library(ggplot2)
library(rCharts)
library(reshape2)
require(scales)
library(shiny)
library(plotly)

#######################################################################################################
#Autor: Ítalo de Pontes Oliveira e Leandro Balby Marinho                                              #
#Os CSV's são gerados mensalmente, assim, para cada arquivo de dados, uma nova variável é atribuida   #
#######################################################################################################
data_filename = "camara_dados.txt"

#######################################################################################################
#Por convensão, decidiu-se utilizar o formato de arquivo CSV, logo o separador sempre será a vírgula  #
#######################################################################################################
data <- read.csv2(file=data_filename, sep=",", header=FALSE, stringsAsFactors=FALSE, na.strings="unknown", dec=".", encoding = "UTF-8")
colnames(data) <-  c("mes","ano","cargo","vinculo","nome","remuneracao_fixa","vantagens_pessoais","remuneracao_eventual","abono_permanencia","descontos","diarias","outros_auxilios","outras_vantagens")

data <- mutate(data, remuneracao_total=remuneracao_fixa+vantagens_pessoais+remuneracao_eventual+abono_permanencia-descontos+diarias+outros_auxilios+outras_vantagens)

ano_max <- max(data$ano)
ano_min <- min(data$ano)

options(scipen=999, OutDec= ",")

camara_recente <- data[data$ano==ano_max,]

remuneracao_total_liquida <- sum(data$remuneracao_total, na.rm=T)

topSalarios <- function(salariosAgregados, column_ref, keeps, size) {
  topSalarios <- salariosAgregados[order(column_ref, decreasing=TRUE)[1:size],]
  rownames(topSalarios) <- NULL
  colnames(topSalarios) <- keeps
  return(topSalarios)
}

keeps <- c("Nome","Cargo","Vnculo","Mês","Ano","Remuneraço Total (R$)")
salariosAgregados <- aggregate(remuneracao_total~nome+cargo+vinculo+mes+ano, FUN=sum, data)
top_servidores_todos <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

gasto_de_referencia <- sum(top_servidores_todos$`Remuneraço Total (R$)`)

todos_deputados <- filter(data, grepl("DEPUTADO", cargo))
todos_deputados_recente <- todos_deputados[todos_deputados$ano==ano_max,]

deputados_acima_teto <- todos_deputados[todos_deputados$remuneracao_total>37476.93,]
deputados_acima_teto_recente <- todos_deputados_recente[todos_deputados_recente$remuneracao_total>37476.93,]

salariosAgregados <- aggregate(remuneracao_total~nome+cargo+vinculo+mes+ano, FUN=sum, todos_deputados)
top_deputados_todos <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

salariosAgregados <- aggregate(remuneracao_total~nome+cargo+vinculo+mes+ano, FUN=sum, todos_deputados_recente)
top_deputados_recente <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

```

**Para se ter ideia dos gastos da Cmara com folha de pagamento dos servidores, só em `r ano_max`, o que foi pago em Licença-Prêmio para apenas dez servidores seria equivalente à:**

Row
-----------------------------------------------------------------------

### ambulancia

```{r custo_de_uma_ambulancia}
valor_de_uma_ambulancia <- 150600
value <- round(gasto_de_referencia/valor_de_uma_ambulancia, 0)
valueBox(value, caption="Ambulâncias novas", icon = "fa-car", color="primary", href="http://www.otempo.com.br/cidades/dezenove-ambul%C3%A2ncias-do-samu-est%C3%A3o-paradas-em-galp%C3%A3o-1.1436254")
```

### bolsas doutorado

```{r bolsa_capes_doutorado}
bolsa_doutorado <- 2200
value <- round(gasto_de_referencia/(bolsa_doutorado*48), 0)
valueBox(value, caption="Alunos de doutorado com Bolsa CAPES por 4 anos", icon = "fa-pencil", color="#2a6592", href="http://www.capes.gov.br/bolsas/valores-de-bolsas")
```

### tratamento cancer

```{r tratamento_cancer}
paciente_cancer <- 10476
value <- round(gasto_de_referencia/paciente_cancer, 0)
valueBox(value, caption="Atendimentos à pacientes com Câncer", icon = "fa-medkit", color="primary", href="http://www2.inca.gov.br/wps/wcm/connect/agencianoticias/site/home/noticias/2016/ministro-da-saude-anuncia-prioridades-para-a-oncologia")
```

### merenda escolar

```{r meses_merenda_escolar}
valor_merenda <- 11.34
value <- paste(round(gasto_de_referencia/(valor_merenda*10^3), 1), " Mil")
valueBox(value, caption="Crianças beneficiadas com merenda escolar", icon = "fa-cutlery", color="#2a6592", href="http://agenciabrasil.ebc.com.br/politica/noticia/2017-02/governo-anuncia-reajustes-para-merenda-escolar")
```

### domestica aposentadoria

```{r domestica_aposentadoria}
domestica_inss <- 120
value <- paste(round(gasto_de_referencia/(domestica_inss*10^3), 1), "Mil")
valueBox(value, caption="Domésticas contribuindo para o INSS", icon = "fa-home", color="primary", href="https://www.domesticalegal.com.br/utilidades/tabela-de-inss/")
```

### asfaltar rodovias

```{r asfaltar_rodovias}
rodovia_quilometro <- 3468000
value <- round(gasto_de_referencia/rodovia_quilometro, 1)
valueBox(value, caption="Quilomêtros de rodovias asfaltadas", icon = "fa-road", color="#2a6592", href="https://189.9.128.64/download/servicos/custo-medio-gerencial/custos-medios-ger.novembro-14.pdf")
```


## Análise da Camara {.tabset .tabset-fade}
